theme: jekyll-theme-minimal
title: Cat Rules the World
logo: /docs/IMG_7395.JPG

affiliation: Cat Planet
email: amaiesc@gmail.com
github_link: https://github.com/amaiesc/study_r
linkedin: https://www.linkedin.com/amaiesc

description: gimme food!

