theme: jekyll-theme-minimal
title: Cats rule the world
description: I love cats!!!
markdown: kramdown
logo: /docs/IMG_1437.JPG
github:
  url: http://example.com/download.zip
  another_url: another value
