theme: jekyll-theme-minimal
title: R.
logo: /docs/icon_b.png
description: about me: I'm a data scientist working for private companies (both in Thailand and Singapore) to build their business models (see my resume above). Occasionally, I am also a lecturer at Psychology Faculty, Chulalongkorn University where I was graduated B.Sc. and M.A. in Social Psychology from.I have this page for the sake of my own storytelling-and-teaching skills but anyone can assess the topics listed here. Hopefully, my cats (aka my students) will learn some basic knowledge in R here.
