theme: jekyll-theme-minimal
title: Cats rule the world
description: I love cats!!!
markdown: kramdown
logo: /docs/IMG_1437.JPG
<!-- Place this tag where you want the button to render. -->
<a class="github-button" href="https://github.com/amaiesc" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" aria-label="Follow @amaiesc on GitHub">Follow @amaiesc</a>
<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
