theme: jekyll-theme-minimal
title: Cat Rules the World
logo: /docs/IMG_7395.JPG

[github_link](https://github.com/amaiesc/study_r)
[email](amaiesc@gmail.com)

l[inkedin](https://www.linkedin.com/amaiesc)

description: gimme food!

